import CardProduct from '@/components/CardItem'
import { Header } from '@/components/Header'
import { GetServerSideProps, InferGetServerSidePropsType } from 'next'
import Head from 'next/head'
export interface ProductProps {
  id: number
  name: string
  brand: string
  description: string
  photo: string
  price: string

}

export default function Home ({products}:InferGetServerSidePropsType<typeof getServerSideProps> ) {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <CardProduct products={products} />
      </main>
    </>
  )
}


export const getServerSideProps: GetServerSideProps<{products: ProductProps[]}> = async (context) => {
  const  response = await fetch('https://mks-challenge-api-frontend.herokuapp.com/api/v1/products?page=1&rows=19&sortBy=id&orderBy=ASC')
  const data = await response.json()
  const  products:ProductProps[] = data.products
 return {
    props: {
      products: products
    }
 }
}